### PR TITLE
Improve CI & fix bug in test spec/didww/client_spec.rb

### LINKED ISSUE #36: Master branch failing to pass tests
Currently, there are issues with the master branch of the didww-v3-ruby repository as it is not passing tests. This is causing difficulty in contributing to the gem.

### PR DESCRIPTION
**Pull request by Ivanov-Anton**
This pull request addresses several issues and improvements in the codebase. Here's a summary of the changes made in each commit:

1. Commit: Ensure the use of "sandbox" as the default api_mode in the test environment.
Description: This commit fixes a failure that occurred when executing a chain of test suites due to a modification of the default api_mode from "sandbox" to "production" in the "spec/didww/client_spec.rb" specification file. To resolve this, I suggest reloading the DIDWW::Client constant after the specific test in "spec/didww/client_spec.rb".

1. Commit: Use Integer instead of Fixnum.
Description: In Ruby, the Fixnum class has been deprecated since Ruby 2.4 and removed in Ruby 3. Instead, the Integer class should be used, which encompasses both Fixnums and Bignums. This commit updates the codebase to use the Integer class.

1. Commit: Use ruby/setup-ruby@v1 instead of deprecated actions/setup-ruby@v1.
Description: The actions/setup-ruby@v1 action has been deprecated. This commit replaces it with the updated ruby/setup-ruby@v1 action to ensure compatibility and proper Ruby setup.

1. Commit: remove support ruby version 2.5, 2.6 and activesupport with 5.0.
Description: Remove support for Ruby versions 2.5 and 2.6, as well as ActiveSupport "~> 5.0", since they are no longer maintained.

closes #36

### CODE REVIEW

**Comment by Ivanov-Anton** [comment]
My suggestion is to create a separate PR after merging these commits, to add support for rails 7 and ruby 3 as additional CI configurations.

File: spec/didww/client_spec.rb [hunk 1]
```diff
@@ -2,9 +2,14 @@
...
-  before(:each) do
+  before do
+    DIDWW.send(:remove_const, :Client)
+    load 'didww/client.rb'
+  end
+
+  after do
     DIDWW.send(:remove_const, :Client)
     load 'didww/client.rb'
   end
```
Comment (gigorok) [inline spec/didww/client_spec.rb:15]:
```
after do
  # restore DIDWW client configuration
    DIDWW::Client.configure do |client|
      client.api_key  = nil
      client.api_mode = :sandbox
    end
  end
```

File: spec/didww/client_spec.rb [hunk 2]
```diff
@@ -2,13 +2,21 @@
...
   let(:api_key) { 'f02c46006f6fa4746cd019abffb0a949' }
   let(:sandbox_uri) { 'https://sandbox-api.didww.com/v3/' }
-  let(:prod_uri) { 'https://sandbox-api.didww.com/v3/' }
+  let(:prod_uri) { 'https://api.didww.com/v3/' }
 
-  before(:each) do
+  before do
     DIDWW.send(:remove_const, :Client)
     load 'didww/client.rb'
   end
```
Comment (gigorok) [inline spec/didww/client_spec.rb:10]: looks like `before` block also is not needed

Comment (Ivanov-Anton) [reply spec/didww/client_spec.rb]: ✅
